### ISSUE TITLE
Empty route unreachable

### ISSUE THREAD

**Issue by jamescheney** [links-lang/links#183]
Since #157, on doing this:
```
addRoute("",foo)
servePages()
```
it no longer seems to be possible to get the result of "foo" by going to `http://localhost:8080` or  `http://localhost:8080/`.  It used to be (I think) that if you used the trailing slash the right thing would happen, but now either case results in "Nope".  (This is the case even if there is an index.html file in the current directory; though from the discussion in #157 I thought that the right behavior might be for index.html to be served if no other route matches.)

On the other hand, doing
```
addRoute("foo",foo)
servePages()
```
does cause the right thing to happen if you visit `http://localhost:8080/foo`.

**Comment by jamescheney** [comment]
(NB.  https://github.com/links-lang/links-tutorial/blob/master/1_hello/hello.links is a concrete example.)

**Comment by jamescheney** [comment]
So it appears the right thing happens if you do

```
addRoute("/",foo)
servePages()
```
I think this is because the empty string parses to an empty list of "/"-separated strings, which is treated the same as a string that does not match any routes.

I think it would be better for `addRoute()` to either raise an error if the route string does not begin with "/", or add a leading "/" if there isn't one.  But I'm not sure of the correct/intended behavior.

**Comment by jgbm** [comment]
It's subtler than that... `addRoute("/", foo)` installs `foo` to handle arbitrary requests, which happen to include the empty request.

Anyway, should be fixed by 4575b83b

**Comment by jamescheney** [comment]
I'm not sure what changed.  `addRoute("",foo)` still does not do a sensible thing; there seems to be no way to reach foo, in particular neither  `http://localhost:8080` or `http://localhost:8080/` work.  

Perhaps what changed is that `addRoute("/",foo)` no longer steals all requests, including to things like `/lib/` (I noticed a lot of 404s for JS library loading before and those seem to have gone away).

I would like to have a canonical way to install a request handler such that visiting the top-level of the server does the right thing.  If the right way is to install at "/" rather than "", then calling addRoute("",foo) should be an error.

**Comment by jamescheney** [comment]
Never mind, I had neglected to recompile.  After recompiling everything is fine.
